on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - run:  make lint
